// automatically generated by the FlatBuffers compiler, do not modify
// JavaScript compatibility wrapper for FlatBuffers v25.2.10

import * as fb from './osrm/engine/api/fbresult.js';

/**
 * @const
 * @namespace
 */
const osrm = osrm || {};

/**
 * @const
 * @namespace
 */
osrm.engine = osrm.engine || {};

/**
 * @const
 * @namespace
 */
osrm.engine.api = osrm.engine.api || {};

/**
 * @const
 * @namespace
 */
osrm.engine.api.fbresult = osrm.engine.api.fbresult || {};

// Map new TypeScript exports to old JavaScript structure
osrm.engine.api.fbresult.FBResult = fb.FBResult;
osrm.engine.api.fbresult.Error = fb.Error;
osrm.engine.api.fbresult.Position = fb.Position;
osrm.engine.api.fbresult.Waypoint = fb.Waypoint;
osrm.engine.api.fbresult.RouteObject = fb.RouteObject;
osrm.engine.api.fbresult.TableResult = fb.TableResult;
osrm.engine.api.fbresult.Leg = fb.Leg;
osrm.engine.api.fbresult.Step = fb.Step;
osrm.engine.api.fbresult.StepManeuver = fb.StepManeuver;
osrm.engine.api.fbresult.ManeuverType = fb.ManeuverType;
osrm.engine.api.fbresult.Annotation = fb.Annotation;
osrm.engine.api.fbresult.Intersection = fb.Intersection;
osrm.engine.api.fbresult.Lane = fb.Lane;
osrm.engine.api.fbresult.Turn = fb.Turn;
osrm.engine.api.fbresult.Metadata = fb.Metadata;
osrm.engine.api.fbresult.Uint64Pair = fb.Uint64Pair;

export { osrm };