language: cpp

sudo: false

compiler: clang

addons:
  apt:
    sources:  [ 'ubuntu-toolchain-r-test', 'george-edison55-precise-backports' ]
    packages: [ 'libstdc++-5-dev', 'cmake', 'cmake-data' ]

matrix:
  exclude:
    - os: linux
  include:
    - os: osx
      osx_image: xcode7
      env: MASON_PLATFORM=ios
    - os: osx
      osx_image: xcode7
      env: MASON_PLATFORM=osx
    - os: linux
      env: MASON_PLATFORM=linux
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v5
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v7
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=arm-v8
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=x86-64
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ABI=mips-64

before_install:
- if [[ ${MASON_PLATFORM} == "osx" || ${MASON_PLATFORM} == "ios" ]]; then brew install cmake ; fi

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}

after_success:
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
