// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Error } from '../../../../osrm/engine/api/fbresult/error.js';
import { RouteObject } from '../../../../osrm/engine/api/fbresult/route-object.js';
import { TableResult } from '../../../../osrm/engine/api/fbresult/table-result.js';
import { Waypoint } from '../../../../osrm/engine/api/fbresult/waypoint.js';
export class FBResult {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsFBResult(bb, obj) {
        return (obj || new FBResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsFBResult(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new FBResult()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    error() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
    }
    code(obj) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new Error()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    }
    dataVersion(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    waypoints(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? (obj || new Waypoint()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    waypointsLength() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    routes(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? (obj || new RouteObject()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    routesLength() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    table(obj) {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? (obj || new TableResult()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    }
    static startFBResult(builder) {
        builder.startObject(6);
    }
    static addError(builder, error) {
        builder.addFieldInt8(0, +error, +false);
    }
    static addCode(builder, codeOffset) {
        builder.addFieldOffset(1, codeOffset, 0);
    }
    static addDataVersion(builder, dataVersionOffset) {
        builder.addFieldOffset(2, dataVersionOffset, 0);
    }
    static addWaypoints(builder, waypointsOffset) {
        builder.addFieldOffset(3, waypointsOffset, 0);
    }
    static createWaypointsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startWaypointsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static addRoutes(builder, routesOffset) {
        builder.addFieldOffset(4, routesOffset, 0);
    }
    static createRoutesVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startRoutesVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static addTable(builder, tableOffset) {
        builder.addFieldOffset(5, tableOffset, 0);
    }
    static endFBResult(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static finishFBResultBuffer(builder, offset) {
        builder.finish(offset);
    }
    static finishSizePrefixedFBResultBuffer(builder, offset) {
        builder.finish(offset, undefined, true);
    }
}
