// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
export class Lane {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsLane(bb, obj) {
        return (obj || new Lane()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsLane(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Lane()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    indications(index) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readInt8(this.bb.__vector(this.bb_pos + offset) + index) : null;
    }
    indicationsLength() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    indicationsArray() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? new Int8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
    }
    valid() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
    }
    static startLane(builder) {
        builder.startObject(2);
    }
    static addIndications(builder, indicationsOffset) {
        builder.addFieldOffset(0, indicationsOffset, 0);
    }
    static createIndicationsVector(builder, data) {
        builder.startVector(1, data.length, 1);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addInt8(data[i]);
        }
        return builder.endVector();
    }
    static startIndicationsVector(builder, numElems) {
        builder.startVector(1, numElems, 1);
    }
    static addValid(builder, valid) {
        builder.addFieldInt8(1, +valid, +false);
    }
    static endLane(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createLane(builder, indicationsOffset, valid) {
        Lane.startLane(builder);
        Lane.addIndications(builder, indicationsOffset);
        Lane.addValid(builder, valid);
        return Lane.endLane(builder);
    }
}
