// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Annotation } from '../../../../osrm/engine/api/fbresult/annotation.js';
import { Step } from '../../../../osrm/engine/api/fbresult/step.js';
export class Leg {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsLeg(bb, obj) {
        return (obj || new Leg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsLeg(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Leg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    distance() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    duration() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    weight() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    summary(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    annotations(obj) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? (obj || new Annotation()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    }
    steps(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? (obj || new Step()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    stepsLength() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startLeg(builder) {
        builder.startObject(6);
    }
    static addDistance(builder, distance) {
        builder.addFieldFloat64(0, distance, 0.0);
    }
    static addDuration(builder, duration) {
        builder.addFieldFloat64(1, duration, 0.0);
    }
    static addWeight(builder, weight) {
        builder.addFieldFloat64(2, weight, 0.0);
    }
    static addSummary(builder, summaryOffset) {
        builder.addFieldOffset(3, summaryOffset, 0);
    }
    static addAnnotations(builder, annotationsOffset) {
        builder.addFieldOffset(4, annotationsOffset, 0);
    }
    static addSteps(builder, stepsOffset) {
        builder.addFieldOffset(5, stepsOffset, 0);
    }
    static createStepsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startStepsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endLeg(builder) {
        const offset = builder.endObject();
        return offset;
    }
}
