// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ManeuverType;
(function (ManeuverType) {
    ManeuverType[ManeuverType["Turn"] = 0] = "Turn";
    ManeuverType[ManeuverType["NewName"] = 1] = "NewName";
    ManeuverType[ManeuverType["Depart"] = 2] = "Depart";
    ManeuverType[ManeuverType["Arrive"] = 3] = "Arrive";
    ManeuverType[ManeuverType["Merge"] = 4] = "Merge";
    ManeuverType[ManeuverType["OnRamp"] = 5] = "OnRamp";
    ManeuverType[ManeuverType["OffRamp"] = 6] = "OffRamp";
    ManeuverType[ManeuverType["Fork"] = 7] = "Fork";
    ManeuverType[ManeuverType["EndOfRoad"] = 8] = "EndOfRoad";
    ManeuverType[ManeuverType["Continue"] = 9] = "Continue";
    ManeuverType[ManeuverType["Roundabout"] = 10] = "Roundabout";
    ManeuverType[ManeuverType["Rotary"] = 11] = "Rotary";
    ManeuverType[ManeuverType["RoundaboutTurn"] = 12] = "RoundaboutTurn";
    ManeuverType[ManeuverType["Notification"] = 13] = "Notification";
    ManeuverType[ManeuverType["ExitRoundabout"] = 14] = "ExitRoundabout";
    ManeuverType[ManeuverType["ExitRotary"] = 15] = "ExitRotary";
})(ManeuverType || (ManeuverType = {}));
