// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ManeuverType {
  Turn = 0,
  NewName = 1,
  Depart = 2,
  Arrive = 3,
  Merge = 4,
  OnRamp = 5,
  OffRamp = 6,
  Fork = 7,
  EndOfRoad = 8,
  Continue = 9,
  Roundabout = 10,
  Rotary = 11,
  RoundaboutTurn = 12,
  Notification = 13,
  ExitRoundabout = 14,
  ExitRotary = 15
}
