// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Leg } from '../../../../osrm/engine/api/fbresult/leg.js';
import { Position } from '../../../../osrm/engine/api/fbresult/position.js';


export class RouteObject {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RouteObject {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRouteObject(bb:flatbuffers.ByteBuffer, obj?:RouteObject):RouteObject {
  return (obj || new RouteObject()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRouteObject(bb:flatbuffers.ByteBuffer, obj?:RouteObject):RouteObject {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RouteObject()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

distance():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

duration():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

weight():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

weightName():string|null
weightName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weightName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

confidence():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

polyline():string|null
polyline(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
polyline(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

coordinates(index: number, obj?:Position):Position|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Position()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

coordinatesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

legs(index: number, obj?:Leg):Leg|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new Leg()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

legsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startRouteObject(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addDistance(builder:flatbuffers.Builder, distance:number) {
  builder.addFieldFloat32(0, distance, 0.0);
}

static addDuration(builder:flatbuffers.Builder, duration:number) {
  builder.addFieldFloat32(1, duration, 0.0);
}

static addWeight(builder:flatbuffers.Builder, weight:number) {
  builder.addFieldFloat32(2, weight, 0.0);
}

static addWeightName(builder:flatbuffers.Builder, weightNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, weightNameOffset, 0);
}

static addConfidence(builder:flatbuffers.Builder, confidence:number) {
  builder.addFieldFloat32(4, confidence, 0.0);
}

static addPolyline(builder:flatbuffers.Builder, polylineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, polylineOffset, 0);
}

static addCoordinates(builder:flatbuffers.Builder, coordinatesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, coordinatesOffset, 0);
}

static startCoordinatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static addLegs(builder:flatbuffers.Builder, legsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, legsOffset, 0);
}

static createLegsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLegsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRouteObject(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRouteObject(builder:flatbuffers.Builder, distance:number, duration:number, weight:number, weightNameOffset:flatbuffers.Offset, confidence:number, polylineOffset:flatbuffers.Offset, coordinatesOffset:flatbuffers.Offset, legsOffset:flatbuffers.Offset):flatbuffers.Offset {
  RouteObject.startRouteObject(builder);
  RouteObject.addDistance(builder, distance);
  RouteObject.addDuration(builder, duration);
  RouteObject.addWeight(builder, weight);
  RouteObject.addWeightName(builder, weightNameOffset);
  RouteObject.addConfidence(builder, confidence);
  RouteObject.addPolyline(builder, polylineOffset);
  RouteObject.addCoordinates(builder, coordinatesOffset);
  RouteObject.addLegs(builder, legsOffset);
  return RouteObject.endRouteObject(builder);
}
}
