// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Intersection } from '../../../../osrm/engine/api/fbresult/intersection.js';
import { Position } from '../../../../osrm/engine/api/fbresult/position.js';
import { StepManeuver } from '../../../../osrm/engine/api/fbresult/step-maneuver.js';
export class Step {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsStep(bb, obj) {
        return (obj || new Step()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsStep(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Step()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    distance() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    duration() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    polyline(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    coordinates(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? (obj || new Position()).__init(this.bb.__vector(this.bb_pos + offset) + index * 8, this.bb) : null;
    }
    coordinatesLength() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    weight() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    name(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    ref(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    pronunciation(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 18);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    destinations(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 20);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    exits(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 22);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    mode(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 24);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    maneuver(obj) {
        const offset = this.bb.__offset(this.bb_pos, 26);
        return offset ? (obj || new StepManeuver()).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
    }
    intersections(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 28);
        return offset ? (obj || new Intersection()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    intersectionsLength() {
        const offset = this.bb.__offset(this.bb_pos, 28);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    rotaryName(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 30);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    rotaryPronunciation(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 32);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    drivingSide() {
        const offset = this.bb.__offset(this.bb_pos, 34);
        return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
    }
    static startStep(builder) {
        builder.startObject(16);
    }
    static addDistance(builder, distance) {
        builder.addFieldFloat32(0, distance, 0.0);
    }
    static addDuration(builder, duration) {
        builder.addFieldFloat32(1, duration, 0.0);
    }
    static addPolyline(builder, polylineOffset) {
        builder.addFieldOffset(2, polylineOffset, 0);
    }
    static addCoordinates(builder, coordinatesOffset) {
        builder.addFieldOffset(3, coordinatesOffset, 0);
    }
    static startCoordinatesVector(builder, numElems) {
        builder.startVector(8, numElems, 4);
    }
    static addWeight(builder, weight) {
        builder.addFieldFloat32(4, weight, 0.0);
    }
    static addName(builder, nameOffset) {
        builder.addFieldOffset(5, nameOffset, 0);
    }
    static addRef(builder, refOffset) {
        builder.addFieldOffset(6, refOffset, 0);
    }
    static addPronunciation(builder, pronunciationOffset) {
        builder.addFieldOffset(7, pronunciationOffset, 0);
    }
    static addDestinations(builder, destinationsOffset) {
        builder.addFieldOffset(8, destinationsOffset, 0);
    }
    static addExits(builder, exitsOffset) {
        builder.addFieldOffset(9, exitsOffset, 0);
    }
    static addMode(builder, modeOffset) {
        builder.addFieldOffset(10, modeOffset, 0);
    }
    static addManeuver(builder, maneuverOffset) {
        builder.addFieldOffset(11, maneuverOffset, 0);
    }
    static addIntersections(builder, intersectionsOffset) {
        builder.addFieldOffset(12, intersectionsOffset, 0);
    }
    static createIntersectionsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startIntersectionsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static addRotaryName(builder, rotaryNameOffset) {
        builder.addFieldOffset(13, rotaryNameOffset, 0);
    }
    static addRotaryPronunciation(builder, rotaryPronunciationOffset) {
        builder.addFieldOffset(14, rotaryPronunciationOffset, 0);
    }
    static addDrivingSide(builder, drivingSide) {
        builder.addFieldInt8(15, +drivingSide, +false);
    }
    static endStep(builder) {
        const offset = builder.endObject();
        return offset;
    }
}
