// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Uint64Pair {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Uint64Pair {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

first():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

second():bigint {
  return this.bb!.readUint64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createUint64Pair(builder:flatbuffers.Builder, first: bigint, second: bigint):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(BigInt(second ?? 0));
  builder.writeInt64(BigInt(first ?? 0));
  return builder.offset();
}

}
