// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Position } from '../../../../osrm/engine/api/fbresult/position.js';
import { Uint64Pair } from '../../../../osrm/engine/api/fbresult/uint64-pair.js';
export class Waypoint {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsWaypoint(bb, obj) {
        return (obj || new Waypoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsWaypoint(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Waypoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    hint(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    distance() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    name(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    location(obj) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? (obj || new Position()).__init(this.bb_pos + offset, this.bb) : null;
    }
    nodes(obj) {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? (obj || new Uint64Pair()).__init(this.bb_pos + offset, this.bb) : null;
    }
    matchingsIndex() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    waypointIndex() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    alternativesCount() {
        const offset = this.bb.__offset(this.bb_pos, 18);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    tripsIndex() {
        const offset = this.bb.__offset(this.bb_pos, 20);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    static startWaypoint(builder) {
        builder.startObject(9);
    }
    static addHint(builder, hintOffset) {
        builder.addFieldOffset(0, hintOffset, 0);
    }
    static addDistance(builder, distance) {
        builder.addFieldFloat32(1, distance, 0.0);
    }
    static addName(builder, nameOffset) {
        builder.addFieldOffset(2, nameOffset, 0);
    }
    static addLocation(builder, locationOffset) {
        builder.addFieldStruct(3, locationOffset, 0);
    }
    static addNodes(builder, nodesOffset) {
        builder.addFieldStruct(4, nodesOffset, 0);
    }
    static addMatchingsIndex(builder, matchingsIndex) {
        builder.addFieldInt32(5, matchingsIndex, 0);
    }
    static addWaypointIndex(builder, waypointIndex) {
        builder.addFieldInt32(6, waypointIndex, 0);
    }
    static addAlternativesCount(builder, alternativesCount) {
        builder.addFieldInt32(7, alternativesCount, 0);
    }
    static addTripsIndex(builder, tripsIndex) {
        builder.addFieldInt32(8, tripsIndex, 0);
    }
    static endWaypoint(builder) {
        const offset = builder.endObject();
        return offset;
    }
}
