// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Position } from '../../../../osrm/engine/api/fbresult/position.js';
import { Uint64Pair } from '../../../../osrm/engine/api/fbresult/uint64-pair.js';


export class Waypoint {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Waypoint {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWaypoint(bb:flatbuffers.ByteBuffer, obj?:Waypoint):Waypoint {
  return (obj || new Waypoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWaypoint(bb:flatbuffers.ByteBuffer, obj?:Waypoint):Waypoint {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Waypoint()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

hint():string|null
hint(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
hint(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

distance():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

location(obj?:Position):Position|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Position()).__init(this.bb_pos + offset, this.bb!) : null;
}

nodes(obj?:Uint64Pair):Uint64Pair|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Uint64Pair()).__init(this.bb_pos + offset, this.bb!) : null;
}

matchingsIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

waypointIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

alternativesCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

tripsIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startWaypoint(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addHint(builder:flatbuffers.Builder, hintOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, hintOffset, 0);
}

static addDistance(builder:flatbuffers.Builder, distance:number) {
  builder.addFieldFloat32(1, distance, 0.0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, locationOffset, 0);
}

static addNodes(builder:flatbuffers.Builder, nodesOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, nodesOffset, 0);
}

static addMatchingsIndex(builder:flatbuffers.Builder, matchingsIndex:number) {
  builder.addFieldInt32(5, matchingsIndex, 0);
}

static addWaypointIndex(builder:flatbuffers.Builder, waypointIndex:number) {
  builder.addFieldInt32(6, waypointIndex, 0);
}

static addAlternativesCount(builder:flatbuffers.Builder, alternativesCount:number) {
  builder.addFieldInt32(7, alternativesCount, 0);
}

static addTripsIndex(builder:flatbuffers.Builder, tripsIndex:number) {
  builder.addFieldInt32(8, tripsIndex, 0);
}

static endWaypoint(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
