repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix]
        files: ^(src/python/|test/python/)
      - id: ruff-format
        files: ^(src/python/|test/python/)
