---
name: "Install Conan"
description: |
  Runs conan install and caches dependencies.

  This action runs `conan install`. All dependencies are cached.

  Prerequisites: Install Python requirements

  Input environment variables:

  OSRM_CONFIG          The build type: Release or Debug.
  BUILD_SHARED_LIBS    Whether to build shared libs or static ones.
  CONAN_CACHE          The Conan cache directory to use.
  CONAN_DOWNLOAD_CACHE The Conan download cache directory to use.

runs:
  using: 'composite'
  steps:
    - name: Restore Conan download cache
      uses: actions/cache/restore@v4
      id: conan-download-cache-restore
      with:
        path: ${{ env.CONAN_DOWNLOAD_CACHE }}
        key: conan-download-${{ runner.os }}-${{ runner.arch }}-${{ env.OSRM_CONFIG }}-${{ hashFiles('conanfile.py') }}
        restore-keys: conan-download-${{ runner.os }}-${{ runner.arch }}-${{ env.OSRM_CONFIG }}-

    - name: Restore Conan cache
      uses: actions/cache/restore@v4
      id: conan-cache-restore
      with:
        path: ${{ env.CONAN_CACHE }}
        key: conan-${{ runner.os }}-${{ runner.arch }}-${{ env.OSRM_CONFIG }}-${{ env.BUILD_SHARED_LIBS}}-${{ hashFiles('conanfile.py', '.conan2/profiles/*', '.conan2/*.conf') }}
        restore-keys: conan-${{ runner.os }}-${{ runner.arch }}-${{ env.OSRM_CONFIG }}-${{ env.BUILD_SHARED_LIBS}}-

    - name: Setup Conan environment
      shell: bash
      run: |
        echo "::group::conan install"
        conan profile detect --force
        conan install -pr ${CONAN_OS_PROFILE} --build=missing -s build_type=${OSRM_CONFIG}
        cat build/conan.env >> $GITHUB_ENV
        conan remove "*" --lru=4w -c
        echo "::endgroup::"

        # outputs
        echo "conan-cache-hit=${{ steps.conan-cache-restore.outputs.cache-hit }}" >> "$GITHUB_OUTPUT"
        echo "conan-cache-primary-key=${{ steps.conan-cache-restore.outputs.cache-primary-key }}" >> "$GITHUB_OUTPUT"
        # probably not very useful
        echo "pip-cache-hit=${{ steps.pip-cache-restore.outputs.cache-hit }}" >> "$GITHUB_OUTPUT"
        echo "pip-cache-primary-key=${{ steps.pip-cache-restore.outputs.cache-primary-key }}" >> "$GITHUB_OUTPUT"

    - name: Debug Conan environment
      shell: bash
      run: |
        echo "::group::cat build/conan.env"
        cat build/conan.env
        echo "::endgroup::"

        echo "::group::ls"
        ls "${CONAN_GENERATORS_DIR}"
        echo "::endgroup::"

        echo "::group::cat conan_toolchain.cmake"
        cat "${CONAN_GENERATORS_DIR}/conan_toolchain.cmake"
        echo "::endgroup::"

        echo "::group::cat CMakePresets.json"
        cat "${CONAN_GENERATORS_DIR}/CMakePresets.json"
        echo "::endgroup::"

        echo "::group::cat conan-build-env.sh"
        cat "build/conan-build-env.sh"
        echo "::endgroup::"

        echo "::group::cat conan-run-env.sh"
        cat "build/conan-run-env.sh"
        echo "::endgroup::"

        echo "::group::Conan cache contents"
        conan list
        echo "::endgroup::"

        # Set Conan build environment for future bash invocations. We cannot simply `cat
        # conan-build-env.sh >> $GITHUB_ENV` because tecnically it is a shell file and
        # may in future version contain commands.
        echo "BASH_ENV=build/conan-build-env.sh" >> $GITHUB_ENV

    - name: Save Conan download cache
      uses: actions/cache/save@v4
      if: always() && steps.conan-download-cache-restore.outputs.cache-hit != 'true'
      with:
        path: ${{ env.CONAN_DOWNLOAD_CACHE }}
        key: ${{ steps.conan-download-cache-restore.outputs.cache-primary-key }}

    - name: Save Conan cache
      uses: actions/cache/save@v4
      if: always() && steps.conan-cache-restore.outputs.cache-hit != 'true'
      with:
        path: ${{ env.CONAN_CACHE }}
        key: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}
