name: Install vcpkg packages on Windows

runs:
  using: composite
  steps:
    - name: Install packages
      run: |
        vcpkg install \
          boost-crc:x64-windows \
          boost-variant:x64-windows \
          bzip2:x64-windows \
          expat:x64-windows \
          lz4:x64-windows \
          sparsehash:x64-windows \
          zlib:x64-windows
      shell: bash

