#ifndef VERSION_HPP
#define VERSION_HPP

#define OSRM_VERSION_MAJOR               6
#define OSRM_VERSION_MINOR               0
#define OSRM_VERSION_PATCH               0
#define OSRM_VERSION_PRERELEASE_BUILD    ""

#define OSRM_VERSION__(A,B,C,D) "v" #A "." #B "." #C D
#define OSRM_VERSION_(A,B,C,D) OSRM_VERSION__(A,B,C,D)
#define OSRM_VERSION OSRM_VERSION_(OSRM_VERSION_MAJOR, OSRM_VERSION_MINOR, OSRM_VERSION_PATCH, OSRM_VERSION_PRERELEASE_BUILD)

#endif // VERSION_HPP
