
sequenceDiagram
    participant U as User
    participant J as Jenkins
    participant D as DockerRegistry
    participant K as Kubernetes

    U ->>+ J: Build OSRM docker 
    Note over U,J: include or NOT include mapdata
    J ->>- D: Push image to registry
    J ->> U: Build done

    U ->> K: Trigger deployment by Kubernetes
    Loop e.g. every 20 minutes
    K ->> K: Rolling update based on docker image
    note over K: update traffic when container startup
    end

