#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

# Regenerates features/support/fbresult_generated.js from the flatbuffers schemas.
#
# The C++ headers are generated at build time by CMake, so they never need this.
# The JavaScript bundle the cucumber steps import is committed to the repository,
# so it has to be rebuilt by hand whenever include/engine/api/flatbuffers/*.fbs
# changes. Forgetting leaves the steps decoding the old field layout.

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT"

SCHEMA_DIR=include/engine/api/flatbuffers
OUTPUT=features/support/fbresult_generated.js

# flatc ships with the vcpkg flatbuffers port, so any configured build has one.
if [ -z "${FLATC:-}" ]; then
    FLATC=$(find build* -path '*tools/flatbuffers/flatc' -type f 2>/dev/null | head -1)
fi
if [ -z "${FLATC:-}" ] && command -v flatc > /dev/null 2>&1; then
    FLATC=flatc
fi
if [ -z "${FLATC:-}" ]; then
    echo "No flatc found. Configure a build so vcpkg installs it, or set FLATC." >&2
    exit 1
fi

echo "Using $("$FLATC" --version)"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

# --gen-all matters here. Without it flatc emits only the types declared in the
# named schema, and it rewrites the namespace barrel once per schema, so passing
# every .fbs file leaves a barrel holding whichever one ran last. Passing just
# fbresult.fbs is enough because it includes route.fbs and table.fbs, which in
# turn include waypoint.fbs and position.fbs.
"$FLATC" --ts --gen-all -o "$WORK" -I "$SCHEMA_DIR" "$SCHEMA_DIR/fbresult.fbs"

# The step definitions import a single nested `osrm` object. flatc emits a flat
# namespace barrel instead, so wrap it.
cat > "$WORK/entry.ts" <<'ENTRY'
import * as fbresult from './osrm/engine/api/fbresult.js';
export const osrm = { engine: { api: { fbresult } } };
ENTRY

# flatbuffers is left external so the bundle uses the npm runtime dependency
# rather than inlining a second copy of it. esbuild writes the source path of
# each chunk as a comment, relative to its working directory, so run it from
# inside the work directory. Running it from the repository root would bake the
# absolute path of the temporary directory into the output and give a different
# result on every machine.
(cd "$WORK" && "$ROOT/node_modules/.bin/esbuild" entry.ts \
    --bundle \
    --format=esm \
    --external:flatbuffers \
    --outfile=bundle.js)

{
    echo "// automatically generated by the FlatBuffers compiler, do not modify"
    echo "// Generated from TypeScript using flatc --ts and esbuild"
    echo "// Regenerate with: npm run regenerate-fbresult"
    echo ""
    cat "$WORK/bundle.js"
} > "$OUTPUT"

echo "Wrote $OUTPUT"
