import path from 'path';

// Somewhere in Monaco
// http://www.openstreetmap.org/#map=18/43.73185/7.41772
export const three_test_coordinates = [[7.41337, 43.72956],
  [7.41546, 43.73077],
  [7.41862, 43.73216]];

export const two_test_coordinates = three_test_coordinates.slice(0, 2);

export const test_tile = {'at': [17059, 11948, 15], 'size': 159125};

// Test files generated by the routing engine; check test/data
let dir;

if (process.env.OSRM_DATA_PATH !== undefined) {
  dir = process.env.OSRM_DATA_PATH;
  console.log(`Setting custom data path to ${data_path}`);
} else {
  dir = process.env.OSRM_TEST_DATA_DIR || 'test/data';
}

const data_path        = path.resolve(path.join(dir, 'ch/monaco.osrm'));
const mld_data_path    = path.resolve(path.join(dir, 'mld/monaco.osrm'));
const test_memory_path = path.resolve(path.join(dir, 'test_memory'));

export { data_path, mld_data_path, test_memory_path };
