name: build and publish container image
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:       
      - name: Check out the repo
        uses: actions/checkout@v2


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Docker meta - debug
        id: metadebug
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            suffix=-debug,onlatest=true

      - name: Docker meta - assertions
        id: metaassertions
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
            suffix=-assertions,onlatest=true
          



      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}




      - name: Build container image - normal
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags:  ${{ steps.meta.outputs.tags  }}
          no-cache: true
          build-args: |
            DOCKER_TAG=${{ join(steps.meta.outputs.tags ) }}


      - name: Build container image - debug
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.metadebug.outputs.tags  }}
          no-cache: true
          build-args: |
            DOCKER_TAG=${{ join(steps.metadebug.outputs.tags ) }}


      - name: Build container image - assertions
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.metaassertions.outputs.tags  }}
          no-cache: true
          build-args: |
            DOCKER_TAG=${{ join(steps.metaassertions.outputs.tags ) }}


            
