name: Python Bindings

on:
  push:
    branches:
      - nn-py-bindings
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build - cp312, Windows amd64
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Restore Conan cache
      id: conan-cache
      uses: actions/cache/restore@v5
      with:
        path: ~/.conan2
        key: v4-conan-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          v4-conan-${{ runner.os }}-

    - name: Run cibuildwheel
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_CONFIG_SETTINGS_WINDOWS: "cmake.define.ENABLE_CONAN=ON"

    - name: Save Conan cache
      uses: actions/cache/save@v5
      if: "!cancelled() && steps.conan-cache.outputs.cache-hit != 'true'"
      with:
        path: ~/.conan2
        key: v4-conan-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-windows-amd64
        path: wheelhouse/*.whl
