name: Monthly Release

on:
  workflow_dispatch:

concurrency:
  group: release-monthly-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build_python_wheels:
    name: Python wheels - ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Windows amd64
            runner: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Restore Conan cache
      id: conan-cache
      if: runner.os == 'Windows'
      uses: actions/cache/restore@v5
      with:
        path: ~/.conan2
        key: v4-conan-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          v4-conan-${{ runner.os }}-

    - name: Run cibuildwheel
      uses: pypa/cibuildwheel@v3.4.0
      env:
        CIBW_CONTAINER_ENGINE: "docker; create_args: --volume /tmp/ccache:/ccache"
        CIBW_ENVIRONMENT_LINUX: "LD_LIBRARY_PATH=/usr/local/lib64:${LD_LIBRARY_PATH} CCACHE_DIR=/ccache"
        CIBW_CONFIG_SETTINGS_MACOS: "cmake.define.CMAKE_CXX_COMPILER_LAUNCHER=ccache cmake.define.CMAKE_C_COMPILER_LAUNCHER=ccache"
        CIBW_CONFIG_SETTINGS_WINDOWS: "cmake.define.ENABLE_CONAN=ON"

    - name: Save Conan cache
      uses: actions/cache/save@v5
      if: "!cancelled() && runner.os == 'Windows' && steps.conan-cache.outputs.cache-hit != 'true'"
      with:
        path: ~/.conan2
        key: v4-conan-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: python-wheels-${{ matrix.name }}
        path: wheelhouse/*.whl
