name: 'Close stale issues'
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *' # every day at 1:30am
permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/stale@v9
        with:
          operations-per-run: 3000
          stale-issue-message: 'This issue seems to be stale. It will be closed in 30 days if no further activity occurs.'
          stale-pr-message: 'This PR seems to be stale. Is it still relevant?'
          days-before-issue-stale: 180 # 6 months
          days-before-issue-close: 30 # 1 month
          days-before-pr-stale: 180 # 6 months
          days-before-pr-close: -1 # never close PRs
          exempt-issue-labels: 'Do Not Stale,Feature Request,Performance,Bug Report,CI,Starter Task,Refactor,Guidance'

  

