name: 'Close stale issues'
on:
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue seems to be stale. It will be closed in 7 days if no further activity occurs.'
          debug-only: true
